### ISSUE TITLE
is_bold crashes on this spreadsheet due to empty font list

### ISSUE THREAD

**Issue by goatchurchprime** [sensiblecodeio/databaker#67]
fname = "nihousingstats.xls"

import urllib.request, urllib.parse
furl = "https://www.communities-ni.gov.uk/sites/default/files/publications/communities/ni-housing-stats-15-16-tables1.xlsx"
req = urllib.request.Request(furl, headers={'User-Agent' : "Sensible code"}) 
xp = urllib.request.urlopen(req).read()
print("Downloaded", len(xp), "bytes")
fout = open(fname, "wb")
fout.write(xp)
fout.close()

from databaker.framework import *
tabs = loadxlstabs(fname)
tabs[0].is_bold()

**Comment by StevenMaude** [comment]
We looked into this. The failure is due to no font index; get None instead and then there's an access on a None index in messytables.

In this case, it's just a peculiar spreadsheet. Opening in LibreOffice and resaving (first as XLSX, then as XLS, if that makes any difference) then allowed this code to run without issue.
